#!/bin/sh

OUT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

CA=$OUT_DIR/certificates

sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $CA/root/ca.cert.pem